name: 'Framed'
description: 'Enforce repos structure using Framed'
inputs:
  template:
    description: 'Provide template location'
    required: false
    default: './framed.yaml'
  version:
    description: 'Provide version of Framed'
    required: false
    default: 'v0.0.7'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: |
        wget https://github.com/mactat/framed/releases/download/${{ inputs.version }}/framed-linux-amd64-${{ inputs.version }}.tar.gz
        tar -xvzf framed-linux-amd64-${{ inputs.version }}.tar.gz
        mv framed /usr/local/bin
        chmod +x /usr/local/bin/framed
      shell: bash
    - run: framed --template ${{ inputs.template }}
      shell: bash