name: onTag
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: Set release name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: "Build for linux"
        run: make release-lin
      - name: "Build for windows"
        run: make release-win
      - name: "Build for macos"
        run: "make release-mac"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*"